// Top-Level Neural Network Inference Module
// Architecture: 784 -> 128 -> 10
// Includes ReLU activation and memory interfaces

module nn_inference_top #(
    parameter DATA_WIDTH = 16,
    parameter ACC_WIDTH = 32
)(
    input  logic        clk,
    input  logic        rst_n,
    input  logic        start,
    output logic        done,
    output logic [3:0]  prediction,     // 0-9 digit prediction
    output logic [31:0] confidence,     // Confidence score
    
    // AXI-Lite slave interface (for MicroBlaze)
    input  logic [31:0] s_axi_awaddr,
    input  logic        s_axi_awvalid,
    output logic        s_axi_awready,
    input  logic [31:0] s_axi_wdata,
    input  logic        s_axi_wvalid,
    output logic        s_axi_wready,
    output logic [1:0]  s_axi_bresp,
    output logic        s_axi_bvalid,
    input  logic        s_axi_bready,
    input  logic [31:0] s_axi_araddr,
    input  logic        s_axi_arvalid,
    output logic        s_axi_arready,
    output logic [31:0] s_axi_rdata,
    output logic [1:0]  s_axi_rresp,
    output logic        s_axi_rvalid,
    input  logic        s_axi_rready
);

    // Layer sizes
    localparam INPUT_SIZE = 784;
    localparam HIDDEN_SIZE = 128;
    localparam OUTPUT_SIZE = 10;
    
    // Memory for input image (784 bytes)
    logic signed [DATA_WIDTH-1:0] input_mem [0:INPUT_SIZE-1];
    
    // Memory for hidden layer activations (128 values)
    logic signed [ACC_WIDTH-1:0] hidden_mem [0:HIDDEN_SIZE-1];
    
    // Memory for output layer (10 values)
    logic signed [ACC_WIDTH-1:0] output_mem [0:OUTPUT_SIZE-1];
    
    // Weight memories (stored in BRAM)
    // Layer 1: 784 x 128 = 100,352 weights
    logic signed [DATA_WIDTH-1:0] weights_layer1 [0:INPUT_SIZE*HIDDEN_SIZE-1];
    logic signed [DATA_WIDTH-1:0] biases_layer1 [0:HIDDEN_SIZE-1];
    
    // Layer 2: 128 x 10 = 1,280 weights
    logic signed [DATA_WIDTH-1:0] weights_layer2 [0:HIDDEN_SIZE*OUTPUT_SIZE-1];
    logic signed [DATA_WIDTH-1:0] biases_layer2 [0:OUTPUT_SIZE-1];
    
    // Initialize weights from memory files (generated by Python)
    initial begin
        $readmemh("../data/weights_layer0.hex", weights_layer1);
        $readmemh("../data/biases_layer0.hex", biases_layer1);
        $readmemh("../data/weights_layer1.hex", weights_layer2);
        $readmemh("../data/biases_layer1.hex", biases_layer2);
    end
    
    // State machine
    typedef enum logic [2:0] {
        IDLE,
        LAYER1_COMPUTE,
        LAYER1_RELU,
        LAYER2_COMPUTE,
        FIND_MAX,
        DONE_STATE
    } state_t;
    
    state_t state, next_state;
    
    // Counters
    logic [$clog2(HIDDEN_SIZE)-1:0] hidden_idx;
    logic [$clog2(OUTPUT_SIZE)-1:0] output_idx;
    logic [3:0] max_idx;
    logic signed [ACC_WIDTH-1:0] max_value;
    
    // Layer 1 computation
    logic layer1_start, layer1_done;
    logic [$clog2(INPUT_SIZE)-1:0] layer1_input_addr;
    logic signed [DATA_WIDTH-1:0] layer1_input_data;
    logic [$clog2(INPUT_SIZE*HIDDEN_SIZE)-1:0] layer1_weight_addr;
    logic signed [DATA_WIDTH-1:0] layer1_weight_data;
    logic [$clog2(HIDDEN_SIZE)-1:0] layer1_bias_addr;
    logic signed [DATA_WIDTH-1:0] layer1_bias_data;
    logic [$clog2(HIDDEN_SIZE)-1:0] layer1_output_addr;
    logic signed [ACC_WIDTH-1:0] layer1_output_data;
    logic layer1_output_valid;
    
    // Layer 2 computation (similar structure)
    logic layer2_start, layer2_done;
    // ... (similar signals for layer 2)
    
    // Instantiate matrix multiplication units
    matrix_vector_mult #(
        .INPUT_SIZE(INPUT_SIZE),
        .OUTPUT_SIZE(HIDDEN_SIZE),
        .DATA_WIDTH(DATA_WIDTH),
        .ACC_WIDTH(ACC_WIDTH)
    ) layer1_mult (
        .clk(clk),
        .rst_n(rst_n),
        .start(layer1_start),
        .done(layer1_done),
        .input_addr(layer1_input_addr),
        .input_data(layer1_input_data),
        .weight_addr(layer1_weight_addr),
        .weight_data(layer1_weight_data),
        .bias_addr(layer1_bias_addr),
        .bias_data(layer1_bias_data),
        .output_addr(layer1_output_addr),
        .output_data(layer1_output_data),
        .output_valid(layer1_output_valid)
    );
    
    // Memory access logic
    assign layer1_input_data = input_mem[layer1_input_addr];
    assign layer1_weight_data = weights_layer1[layer1_weight_addr];
    assign layer1_bias_data = biases_layer1[layer1_bias_addr];
    
    // Write to hidden memory with ReLU
    always_ff @(posedge clk) begin
        if (layer1_output_valid) begin
            // ReLU activation: max(0, x)
            hidden_mem[layer1_output_addr] <= (layer1_output_data > 0) ? layer1_output_data : '0;
        end
    end
    
    // State machine for inference pipeline
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= IDLE;
            hidden_idx <= '0;
            output_idx <= '0;
            max_idx <= '0;
            max_value <= '0;
        end else begin
            state <= next_state;
            
            case (state)
                IDLE: begin
                    if (start) begin
                        hidden_idx <= '0;
                        output_idx <= '0;
                        max_idx <= '0;
                        max_value <= $signed(-32'h7FFFFFFF);  // Very negative
                    end
                end
                
                FIND_MAX: begin
                    if (output_idx < OUTPUT_SIZE) begin
                        if (output_mem[output_idx] > max_value) begin
                            max_value <= output_mem[output_idx];
                            max_idx <= output_idx[3:0];
                        end
                        output_idx <= output_idx + 1;
                    end
                end
            endcase
        end
    end
    
    // Next state logic
    always_comb begin
        next_state = state;
        layer1_start = 1'b0;
        layer2_start = 1'b0;
        done = 1'b0;
        
        case (state)
            IDLE: begin
                if (start) begin
                    next_state = LAYER1_COMPUTE;
                    layer1_start = 1'b1;
                end
            end
            
            LAYER1_COMPUTE: begin
                if (layer1_done) begin
                    next_state = LAYER2_COMPUTE;
                    layer2_start = 1'b1;
                end
            end
            
            LAYER2_COMPUTE: begin
                if (layer2_done) begin
                    next_state = FIND_MAX;
                end
            end
            
            FIND_MAX: begin
                if (output_idx == OUTPUT_SIZE) begin
                    next_state = DONE_STATE;
                end
            end
            
            DONE_STATE: begin
                done = 1'b1;
                next_state = IDLE;
            end
        endcase
    end
    
    // Output assignments
    assign prediction = max_idx;
    assign confidence = max_value[31:0];

    // TODO: Implement AXI-Lite interface for MicroBlaze communication
    // This allows loading input images and reading results

endmodule
